### PR TITLE
Various panics fixes

### LINKED ISSUE #67: Panic on empty Application name
SPOA crashes if `app` is not set.

Test `coraza.cfg`:
```
spoe-message coraza-req
    args app=req.hdr(test-header) ...
```

```
2023-06-09 13:20:12 time="2023-06-09T10:20:12Z" level=info msg="spoe: listening on [::]:9000"
2023-06-09 13:20:20 panic: interface conversion: interface {} is nil, not string
2023-06-09 13:20:20 
2023-06-09 13:20:20 goroutine 13 [running]:
2023-06-09 13:20:20 coraza-spoa/internal.(*SPOA).processRequest(0xc001115380, {{0xc000596008?, 0xa?}, 0xc0007740a0?})
2023-06-09 13:20:20 /build/internal/request.go:60 +0x26b4
2023-06-09 13:20:20 coraza-spoa/internal.(*SPOA).Start.func1(0xc0013c0040)
2023-06-09 13:20:20 /build/internal/spoa.go:56 +0x95
2023-06-09 13:20:20 github.com/criteo/haproxy-spoe-go.(*conn).handleNotify(0xc000774000, {0x3, 0x1, 0x15, 0x1, {0xc000596007, 0xef, 0x3ff5}, {0xc000596000, 0x3ffc, ...}}, ...)
2023-06-09 13:20:20 /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.6/notify.go:109 +0xea
2023-06-09 13:20:20 github.com/criteo/haproxy-spoe-go.(*conn).runWorker(0xc000774000, {0x3, 0x1, 0x15, 0x1, {0xc000596007, 0xef, 0x3ff5}, {0xc000596000, 0x3ffc, ...}}, ...)
2023-06-09 13:20:20 /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.6/conn.go:153 +0x7b
2023-06-09 13:20:20 created by github.com/criteo/haproxy-spoe-go.(*conn).run
2023-06-09 13:20:20 /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.6/conn.go:136 +0xbb0
2023-06-09 13:20:12 Loading 1 applications
2023-06-09 13:20:21 Loading 1 applications
2023-06-09 13:20:21 time="2023-06-09T10:20:21Z" level=info msg="spoe: listening on [::]:9000"
2023-06-09 13:20:22 time="2023-06-09T10:20:22Z" level=info msg="spoe session ending with: write frame: write tcp 172.25.0.3:9000->172.25.0.4:59074: write: connection reset by peer"
2023-06-09 13:20:22 time="2023-06-09T10:20:22Z" level=warning msg="spoe: error handling connection: write frame: write tcp 172.25.0.3:9000->172.25.0.4:59074: write: connection reset by peer"
```

### PR DESCRIPTION
**Pull request by zc-devs**
Closes #67 and #56.

- refactored message parsing
- introduced custom message, request and response
- fixed both panics
- fixed response body processing

### CODE REVIEW

File: internal/message.go [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+package internal
+
+import (
+	"fmt"
+	"net"
+
+	spoe "github.com/criteo/haproxy-spoe-go"
+)
+
+type message struct {
```
Comment (jcchavezs) [inline internal/message.go:13]: I'd rather do something functions to get values from the map as string/int/ip.

```
func getString(args map[string]interface{}, key string) (string, error) {
   ...
}
```

Adding new struct to fetch values from a map looks overkill unless there are really important logic.

cc @anuraaga

File: internal/spoa.go [hunk 2]
```diff
@@ -229,3 +229,167 @@ func New(conf *config.Config) (*SPOA, error) {
...
+}
+
+func (s *SPOA) processRequest(spoeMsg spoe.Message) ([]spoe.Action, error) {
+	var (
+		err error
+		req *request
+		app *application
+		tx  types.Transaction
+	)
+
```
Comment (jcchavezs) [inline internal/spoa.go:261]: First please check if the RuleEngine is on/off, check https://github.com/corazawaf/coraza/blob/main/http/middleware.go#L132

**Comment by jcchavezs** [comment]
Could you please add some unit tests to functions?

File: internal/spoa.go [hunk 3]
```diff
@@ -229,3 +229,169 @@ func New(conf *config.Config) (*SPOA, error) {
...
+		return nil, err
+	}
+
+	app, err = s.getApplication(req.app)
+	if err != nil {
+		return nil, err
+	}
+
+	tx = app.waf.NewTransactionWithID(req.id)
+	if tx.IsRuleEngineOff() {
```
Comment (jcchavezs) [inline internal/spoa.go:293]: Do we really need to execute all the previous code if ruleEngine is off?

Comment (zc-devs) [reply internal/spoa.go:293]: We need [application at least](https://github.com/zc-devs/coraza-spoa/blob/d1a3d83894ea675ed2709ceb5c8ae5b35ee4a6e1/internal/spoa.go#L198-L209). Then we could get [rule engine status from WAF](https://github.com/corazawaf/coraza/blob/5ffc3a359c8ebf3f0890aa845e611834669066f6/internal/corazawaf/waf.go#L57), if it would be public interface. [In public interface there are only transactions constructors](https://github.com/corazawaf/coraza/blob/5ffc3a359c8ebf3f0890aa845e611834669066f6/waf.go#L21-L25). So, I think we need  to execute all previous code.

File: internal/message.go [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+func getString(args map[string]interface{}, key string) (string, error) {
+	argVal, exist := args[key]
+	if exist && argVal != nil {
+		val, ok := argVal.(string)
+		if ok {
+			return val, nil
+		}
+	}
+
+	return "", fmt.Errorf("invalid argument for %s, string expected, got %v", key, argVal)
```
Comment (anuraaga) [inline internal/message.go:20]: IIUC, this error should be returned if not `ok` above, while here it is the not exists case, so not an error

Comment (zc-devs) [reply internal/message.go:20]: How to signal caller that there is no such key in the map/message? Is below code OK?
```

func getString(args map[string]interface{}, key string) (string, bool, error) {
	argVal, exist := args[key]
	if !exist {
		return "", false, nil
	}
	if argVal == nil {
		return "", true, nil
	}
	val, ok := argVal.(string)
	if !ok {
		return "", true, fmt.Errorf("invalid argument for %s, string expected, got %v", key, argVal)
	}
	return val, true, nil
}
```

Comment (zc-devs) [reply internal/message.go:20]: `coraza-spoa` requires `method` field in the message.
1. message `app=simple_app method=  path...` - variable value set up  issue in HAProxy (probably [haproxy.cfg](https://github.com/corazawaf/coraza-spoa/blob/main/docker/haproxy/haproxy.cfg);
2. message `app=simple_app path...` - message definition issue in HAProxy [SPOE config](https://github.com/corazawaf/coraza-spoa/blob/main/docker/haproxy/coraza.cfg).

Comment (anuraaga) [reply internal/message.go:20]: Returning a `bool` seems fine - from what it looks like some fields are required and some aren't so the caller needs to determine whether it's an error or not, not this utility. Or otherwise we would need two versions of each, `getFoo` and `getFooRequired` or similar, but maybe too much

Comment (jcchavezs) [reply internal/message.go:20]: Still we might need to learn about the error on retrieval. How about

```go
var ErrNotFound = errors.New("key not found")

func getString(args map[string]interface{}, key string) (string, error) {
	argVal, exist := args[key]
	if !exist {
		return "", errNotFound
	}
	if argVal == nil {
		return "", nil
	}
	val, ok := argVal.(string)
	if !ok {
		return "", fmt.Errorf("invalid argument for %s, string expected, got %v", key, argVal)
	}
	return val, nil
}
```

so that we can flag when the key isn't in the map and return a `ErrNotFound` to the upstream function letting them decide what happens if not found and finally another error in case the data isn't correct (hence programatic error).

Comment (zc-devs) [reply internal/message.go]: > the caller needs to determine whether it's an error or not
Already does:
```
	req.method, err = getString(args, "method")
	if err != nil {
		return nil, err
	}
	req.path, err = getString(args, "path")
	if err != nil {
		fmt.Println(err.Error())
	}
	req.body, _ = getByteArray(args, "body")
```

File: internal/spoa.go [hunk 5]
```diff
@@ -229,3 +229,169 @@ func New(conf *config.Config) (*SPOA, error) {
...
+			}
+		}
+	}()
+
+	req, err = NewRequest(spoeMsg)
+	if err != nil {
+		return nil, err
+	}
+
+	app, err = s.getApplication(req.app)
```
Comment (jcchavezs) [inline internal/spoa.go:287]: I would get the app from the spoeMsg and get the request right before we would use it.

File: internal/response.go [hunk 6]
```diff
@@ -6,113 +6,49 @@ package internal
...
+	resp.status, err = getInt(args, "status")
 	if err != nil {
 		return nil, err
 	}
-	if it != nil {
-		return s.processInterruption(it, hit), nil
+
+	resp.headers, err = getString(args, "headers")
+	if err != nil {
+		fmt.Println(err.Error())
```
Comment (jcchavezs) [inline internal/response.go:48]: Instead of fmt.Println could we inject the logger from the app?

Comment (zc-devs) [reply internal/response.go:48]: Let's deal with logging in  #70.

File: internal/spoa.go (hunk 5 above)
Comment (zc-devs) [reply internal/spoa.go:287]: I don't get it. What problem do you try to solve?

From `spoeMsg` only application name can be obtained. Application != application name.

Also in request `request` and `respone` application name is already converted to string and 'validated'.

Comment (zc-devs) [reply internal/spoa.go:287]: Is [c490c9f](https://github.com/corazawaf/coraza-spoa/pull/68/commits/c490c9f2e499bd277a9005d76bb207cb591fc6fc) looks OK?

**Review by anuraaga — APPROVED** [review]

**Comment by jcchavezs** [comment]
Awesome work!
