### PR TITLE
Fixed allowing action & HAProxy logging

### LINKED ISSUE #73: Argument version and headers not found
Hey there, thank you for aiming to replace Trustwave ModSecurity. I have been following the instruction to setup coraza-spoa with haproxy and finally got it running. I am not seeing it block however.

The agent reports the below on every single request:

`INFO[0000] spoe: listening on 127.0.0.1:9000
Argument 'version' not found
Argument 'headers' not found`

Haproxy log shows the following:

`Jul 11 13:15:41 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-frontend-http-request> sid=17 st=0 0/0/0/0/1 1/1 0/0 0/27
Jul 11 13:15:41 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-frontend-http-request> sid=17 st=0 0/0/0/0/1 1/1 0/0 0/27
Jul 11 13:15:41 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-http-response> sid=17 st=0 0/0/0/0/0 1/1 0/0 0/28
Jul 11 13:15:41 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-http-response> sid=17 st=0 0/0/0/0/0 1/1 0/0 0/28
Jul 11 13:15:41 test haproxy[222]: 192.168.1.10:64257 [11/Jul/2023:13:15:41.954] test test_backend/s1 0/0/1/1/0/1/3/6 200 3383 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/1.1" 1ec2bbea-a85f-44da-8e21-d7f382b7bc7b spoa-error: - waf-hit: 0
Jul 11 13:15:42 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-frontend-http-request> sid=19 st=0 0/0/0/0/0 1/1 0/0 0/29
Jul 11 13:15:42 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-frontend-http-request> sid=19 st=0 0/0/0/0/0 1/1 0/0 0/29
Jul 11 13:15:42 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-http-response> sid=19 st=0 0/0/0/0/0 1/1 0/0 0/30
Jul 11 13:15:42 test haproxy[222]: SPOE: [coraza-agent] <EVENT:on-http-response> sid=19 st=0 0/0/0/0/0 1/1 0/0 0/30
Jul 11 13:15:42 test haproxy[222]: 192.168.1.10:64257 [11/Jul/2023:13:15:41.961] test test_backend/s1 0/63/0/63/0/0/1/64 404 433 - - ---- 1/1/0/0/0 0/0 "GET /favicon.ico HTTP/1.1" 5bd81c35-f252-4c44-9ac1-22f17983b228 spoa-error: - waf-hit: 0`

The haproxy config is defined as in the sample from the git project.

`filter spoe engine coraza config /etc/coraza-spoa/coraza.cfg`

and

 `http-request deny if { var(txn.coraza.fail) -m int eq 1 }`
    `http-response deny if { var(txn.coraza.fail) -m int eq 1 }`
    `http-request deny deny_status 504 if { var(txn.coraza.error) -m int gt 0 }`
    `http-response deny deny_status 504 if { var(txn.coraza.error) -m int gt 0 }`
    `use_backend test_backend`

backend is:

`backend test_backend`
    `mode http`
    `server s1 127.0.0.1:8080`

`backend coraza-spoa`
    `mode tcp`
    `server s1 127.0.0.1:9000`

This:

`curl http://serverip/\?x\=/etc/passwd`

Results in the request being passed to apache which is listening on port 8080 same server.
Browsing to the url results in the same.

Corerules are loaded and configured as per example in docs.

### PR DESCRIPTION
**Pull request by zc-devs**
Closes #73 

[log.txt](https://github.com/corazawaf/coraza-spoa/files/12031229/log.txt)

### CODE REVIEW

File: internal/spoa.go [hunk 1]
```diff
@@ -99,14 +85,15 @@ func (s *SPOA) processInterruption(it *types.Interruption, code int) []spoe.Acti
 	}
 }
 
-func (s *SPOA) message(code int) []spoe.Action {
-	return []spoe.Action{
+func (s *SPOA) allowAction() []spoe.Action {
```
Comment (zc-devs) [inline internal/spoa.go:88]: Make constant

**Review by jcchavezs — COMMENTED** [review]
can we add some tests?

File: docker/e2e/e2e.sh [hunk 2]
```diff
@@ -159,4 +171,29 @@ check_status "${url_echo}" 403 --user-agent "Grabber/0.1 (X11; U; Linux i686; en
 echo "[${step}/${total_steps}] True negative GET request with user-agent"
 check_status "${url_echo}" 200 --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
 
+# Find Allow action
```
Comment (jcchavezs) [inline docker/e2e/e2e.sh:174]: This is interesting. Finally someone takes logging seriously <3
